ALTER TABLE ncr_ride_bookings RENAME COLUMN "Booking ID"                           TO booking_id;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Customer ID"                          TO customer_id;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Date"                                 TO booking_date;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Time"                                 TO booking_time;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Vehicle Type"                         TO vehicle_type;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Pickup Location"                      TO pickup_location;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Drop Location"                        TO drop_location;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Avg VTAT"                             TO avg_vtat;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Avg CTAT"                             TO avg_ctat;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Cancelled Rides by Customer"          TO cancelled_rides_by_customer;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Reason for cancelling by Customer" TO customer_cancellation_reason;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Cancelled Rides by Driver"            TO cancelled_rides_by_driver;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Driver Cancellation Reason"           TO driver_cancellation_reason;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Incomplete Rides"                     TO incompleted_rides;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Incomplete Rides Reason"              TO incompleted_rides_reason;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Booking Value"                        TO booking_value;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Ride Distance"                        TO ride_distance;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Driver Ratings"                       TO driver_ratings;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Customer Rating"                      TO customer_ratings;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Booking Status"                       TO booking_status;
ALTER TABLE ncr_ride_bookings RENAME COLUMN "Payment Method"                       TO payment_method;