UPDATE ncr_ride_bookings SET "Avg VTAT" = 0 WHERE "Avg VTAT" = 'null';
UPDATE ncr_ride_bookings SET "Avg CTAT" = 0 WHERE "Avg CTAT" = 'null';
UPDATE ncr_ride_bookings SET "Cancelled Rides by Customer" = 0 WHERE "Cancelled Rides by Customer" = 'null';
UPDATE ncr_ride_bookings SET "Reason for cancelling by Customer" = 'invalid' WHERE "Reason for cancelling by Customer" = 'null';
UPDATE ncr_ride_bookings SET "Cancelled Rides by Driver" = 0 WHERE "Cancelled Rides by Driver" = 'null';
UPDATE ncr_ride_bookings SET "Driver Cancellation Reason" = 'invalid' WHERE "Driver Cancellation Reason" = 'null';
UPDATE ncr_ride_bookings SET "Incomplete Rides" = 0 WHERE "Incomplete Rides" ILIKE 'null';
UPDATE ncr_ride_bookings SET "Incomplete Rides Reason" = 'invalid' WHERE "Incomplete Rides Reason"  = 'null';
UPDATE ncr_ride_bookings SET "Booking Value" = 0 WHERE "Booking Value" = 'null';
UPDATE ncr_ride_bookings SET "Ride Distance" = 0 WHERE "Ride Distance" = 'null';
UPDATE ncr_ride_bookings SET "Driver Ratings" = 0 WHERE "Driver Ratings" = 'null';
UPDATE ncr_ride_bookings SET "Customer Rating" = 0 WHERE "Customer Rating" = 'null';
UPDATE ncr_ride_bookings SET "Payment Method" = 'invalid' WHERE "Payment Method" = 'null';