apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-cloudflared
  namespace: workshop-ghaza
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pg-cloudflared
  template:
    metadata:
      labels:
        app: pg-cloudflared
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ping_group_range
          value: "65532 65532"
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: pg-tunnel-token
              key: token
        command:
        - cloudflared
        - tunnel
        - --no-autoupdate
        - --loglevel
        - debug
        - --metrics
        - 0.0.0.0:2000
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
